const carsData = [
  {
    id: 1,
    manufacturer: "GMC",
    model: "Acadia",
    year: 2009,
    vin: "2HNYD2H47CH518367",
    color: "Puce",
    image: "/cartest.jpg",
  },
  {
    id: 2,
    manufacturer: "Hyundai",
    model: "Sonata",
    year: 2010,
    vin: "WBS3R9C54FK406898",
    color: "Pink",
    image: "/cartest.jpg",
  },
  {
    id: 3,
    manufacturer: "Toyota",
    model: "Sequoia",
    year: 2009,
    vin: "1G6AK5SX7D0126192",
    color: "Blue",
    image: "/cartest.jpg",
  },
  {
    id: 4,
    manufacturer: "Mazda",
    model: "MX-6",
    year: 1997,
    vin: "WAUAVAFDXCN369314",
    color: "Indigo",
    image: "/cartest.jpg",
  },
  {
    id: 5,
    manufacturer: "Toyota",
    model: "T100",
    year: 1998,
    vin: "WAUBVAFA5AN691348",
    color: "Indigo",
    image: "/cartest.jpg",
  },
  {
    id: 6,
    manufacturer: "Ford",
    model: "F-Series Super Duty",
    year: 2012,
    vin: "3VW1K7AJ9CM173822",
    color: "Teal",
    image: "/cartest.jpg",
  },
  {
    id: 7,
    manufacturer: "Ford",
    model: "Bronco",
    year: 1985,
    vin: "1G6DH8EY7B0539518",
    color: "Green",
    image: "/cartest.jpg",
  },
  {
    id: 8,
    manufacturer: "Honda",
    model: "S2000",
    year: 2009,
    vin: "JHMFA3F26AS111643",
    color: "Indigo",
    image: "/cartest.jpg",
  },
  {
    id: 9,
    manufacturer: "BMW",
    model: "8 Series",
    year: 1995,
    vin: "WAUKH74FX7N727102",
    color: "Indigo",
    image: "/cartest.jpg",
  },
  {
    id: 10,
    manufacturer: "Lincoln",
    model: "Continental",
    year: 1997,
    vin: "1FTWX3B58AE422194",
    color: "Orange",
    image: "/cartest.jpg",
  },
];

export default carsData;
